services:

    Gewebe\SyliusVATPlugin\EventListener\LoginListener:
        arguments:
            - '@validator'
            - '%gewebe_sylius_vat_plugin.revalidate.on_login%'
            - '%gewebe_sylius_vat_plugin.revalidate.expiration_days%'
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
