services:

    gewebe_sylius_vat_plugin.command.eu_vat_rates:
        class: Gewebe\SyliusVATPlugin\Command\EuInstallCommand
        arguments:
            - '@gewebe_sylius_vat_plugin.eu_vat_rates'
            - '@sylius.factory.country'
            - '@sylius.repository.country'
            - '@sylius.factory.zone'
            - '@sylius.repository.zone'
            - '@sylius.factory.tax_rate'
            - '@sylius.repository.tax_rate'
            - '@sylius.factory.tax_category'
            - '@sylius.repository.tax_category'
        tags:
            - { name: console.command }

    gewebe_sylius_vat_plugin.eu_vat_rates:
        class: Gewebe\SyliusVATPlugin\Vat\Rates\EuRates
        arguments:
            - '@gewebe_sylius_vat_plugin.rates'

    gewebe_sylius_vat_plugin.rates:
        class: Ibericode\Vat\Rates
        arguments:
            - '%kernel.cache_dir%/vat-rates.json'
            - 86400
