services:

    # Order processor
    gewebe_sylius_vat_plugin.order_processor:
        class: Gewebe\SyliusVATPlugin\OrderProcessing\VatNumberOrderProcessor
        arguments:
            - '%gewebe_sylius_vat_plugin.order.recalculate%'
        tags:
            - { name: sylius.order_processor, priority: 0 }
