services:

    gewebe_sylius_vat_plugin.validator:
        class: Gewebe\SyliusVATPlugin\Validator\Constraints\VatNumberValidator
        arguments:
            - '@gewebe_sylius_vat_plugin.eu_vat_validator'
            - '%gewebe_sylius_vat_plugin.validate.is_active%'
            - '%gewebe_sylius_vat_plugin.validate.country%'
            - '%gewebe_sylius_vat_plugin.validate.existence%'
        tags:
            - { name: validator.constraint_validator }

    gewebe_sylius_vat_plugin.eu_vat_validator:
        class: Gewebe\SyliusVATPlugin\Vat\Number\EuValidator
        arguments:
            - '@gewebe_sylius_vat_plugin.ibericode_vat.validator'

    gewebe_sylius_vat_plugin.ibericode_vat.validator:
        class: Ibericode\Vat\Validator
