
gweb_sylius_vat:
    order:
        recalculate: true
    validate:
        format: true
        country: true
        existence: true
    revalidate:
        on_login: true
        expiration_days: 30
