
gewebe_sylius_vat:
    order:
        recalculate: true
    validate:
        is_active: true
        country: true
        existence: true
    required:
        default: false
        company: false
        countries:
    revalidate:
        on_login: true
        expiration_days: 30
